import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { Toaster } from "react-hot-toast";
import { ibarra } from "./font";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Petr Krajcigr, Finance HB",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cs">
      <body className={`${inter.className} ${ibarra.variable} `}>
        <Navbar />
        {children}
        <Footer />
        <Toaster
          toastOptions={{
            style: {
              textAlign: "center",
            }
          }}
        />
      </body>
    </html>
  );
}
