import type { Metadata } from "next";
import { Inter, } from "next/font/google";
import "./globals.css";
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { Toaster } from "react-hot-toast";
import { ibarra } from "./font";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Petr Krajcigr, Finance HB",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cs">
      <body className={`${inter.className} ${ibarra.variable} `}>
        {(await draftMode()).isEnabled && (
          <a
            className="fixed right-0 bottom-0 bg-blue-500 text-white p-4 m-4"
            href="/api/draft-mode/disable"
          >
            Disable preview mode
          </a>
        )}
        <Navbar />
        {children}
        <Footer />
        <Toaster
          toastOptions={{
            style: {
              textAlign: "center",
            }
          }}
        />
        {(await draftMode()).isEnabled && <VisualEditing />}
      </body>
    </html>
  );
}
